### ISSUE TITLE
Review -00 draft text

### ISSUE THREAD

**Issue by italobusi** [aguoietf/ietf-ccamp-optical-path-computation#13]
Review the -00 version of the draft and provide comments

**Comment by danielkinguk** [comment]
A few suggestions attached.
 
[draft-gbb-ccamp-optical-path-computation-yang-00-dk-review.docx](https://github.com/aguoietf/ietf-ccamp-optical-path-computation/files/8195946/draft-gbb-ccamp-optical-path-computation-yang-00-dk-review.docx)
