### ISSUE TITLE
Add optical impairment-related constraints to path computation

### ISSUE THREAD

**Issue by aguoietf** [aguoietf/ietf-ccamp-optical-path-computation#14]
Candidates for consideration:
- QoT (Q-factor and/or BER)
- G-SNR

**Comment by ggalimba56** [comment]
In flexigrid networks the optical impairments constraints are not very different from WSON networks.
It is very common to calculate the circuit (or tunnel) G-SNR and use its value to match against the Transceiver G-SNR robustness. If the two values are compatible the probability that the new tunnel works is very high (wit usually 0.5dB margin).
Other parameter that can be considered are the total tunnel Chromatic Dispersion (CD) and the Transceiver capability to compensate it. Finally the, for a more accurate optical feasibility, the PMD and PDL can be calculated and checked against the transceiver capabilities.

**Comment by italobusi** [comment]
> It is very common to calculate the circuit (or tunnel) G-SNR and use its value to match against the Transceiver G-SNR robustness. If the two values are compatible the probability that the new tunnel works is very high (wit usually 0.5dB margin).

@aguoietf : there are applications that requires the flexibility to specify a G-SNR different than the Transceiver G-SNR robustness

QoT (Q-factor and/or BER) needs further investigation

**Comment by italobusi** [comment]
**2022-02-03 Call**

Agreement to make the G-SNR margin configurable by the user

Add a new optional attribute:
- name: gsnr-margin
- type: decimal64 (or existing typedef for dB)
- unit: dB
- default: implementation specific (to be clarified in the description)

**Comment by sergiobelotti** [comment]
2022-02-10 call:
gsnr-margin and Q-factor are both parameters that can be configured by user. 
gsnr-margin can overwrite what is provided by transceiver specification (osnr-min, q-factor-min as represented in optical impairments).
Es: I can have a path with OSNR = 9, at receiver you can have by specification OSNR-min = 10, and so the path would be not feasible. But if the user put an OSNR-margin = -2, that means OSNR-min becomes 8, and the path is feasible.
Q-factor needs a clear definition.

**Comment by agva123** [comment]
From gsnr-margin and minimum gsnr on the transceiver, one can estimate a receiving gsnr, which can then be used to calculate Q-factor and pre-FEC BER. Perhaps it is better to just keep the gsnr-margin parameter on the flexgrid tunnel specification.

**Comment by aguoietf** [comment]
From gsnr-margin and minimum gsnr on the transceiver, one can estimate a receiving gsnr, which can then be used to calculate Q-factor and pre-FEC BER. Perhaps it is better to just keep the gsnr-margin parameter on the flexgrid tunnel specification.

**Comment by italobusi** [comment]
**2022-02-17 Call**

**OSNR or GSNR?**

The transceiver spec defines the OSNR-min that characterize the transceiver without considering linear effects. For the path the GSNR is computed (estimated) and this value is compared with the OSNR-min, which includes some industrial and EOL margins 

Example:
- path GSNR = 9 dB
- transceiver mode min-OSNR 7dB
  - with no gsnr-marging, the path is feasible
  - with 3 dB gsnr-marging the path becomes unfeasible

**Should the gsnr-marging be positive or could it be also negative?**

A negative gsnr-marging can be risky. However, the margins used are sometimes too conservative.

**Comment by italobusi** [comment]
2022-02-24 Call

> Add a new optional attribute as output of path computation to report the computed gsnr of the path
> 

Agreed: the attribute should be called estimated-gsnr

> These attributes need to be defined both for path computation and tunnel models (per path)

Agreed: the definitions should be developed within a grouping in L0-types-ext and imported by the path computation and tunnel models
